services:
  proxy:
    image: caddy:alpine
    restart: always
    ports:
      - "5823:443"
      - "5823:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./ssl:/etc/caddy/certs

  # https://docs.openwebui.com/getting-started/quick-start
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    restart: always
    volumes:
      - ./data:/app/backend/data

  # https://docs.all-hands.dev/usage/llms/local-llms
  openhands:
    image: docker.all-hands.dev/all-hands-ai/openhands:0.44
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ~/.openhands:/.openhands
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      SANDBOX_RUNTIME_CONTAINER_IMAGE: docker.all-hands.dev/all-hands-ai/runtime:0.44-nikolaik
      LOG_ALL_EVENTS: true

  # No Metal or ARM Support
  # USING HOMEBREW VERSION ATM
  # https://github.com/huggingface/text-embeddings-inference#docker
  # hftei:
  #   image: ghcr.io/huggingface/text-embeddings-inference:1.7
  #   restart: always
  #   platform: linux/arm64
